### ISSUE TITLE
I got an extra text in rendered table

### ISSUE THREAD

**Issue by chrvip** [benjypng/logseq-tablerender-plugin#8] opened 2022-03-29 07:04 UTC
![image](https://user-images.githubusercontent.com/536916/160552892-bcbd3a25-6b0e-41e5-9025-13313868360e.png)

**Comment by benjypng** [comment] 2022-04-08 07:47
Hmm, that looks like a block id from somewhere. Are you able to reproduce the same bug on other tables?

**Comment by benjypng** [comment] 2022-04-20 05:05
Fixed in v1.9.1

**Closed as completed by benjypng** 2022-04-20 05:05 UTC
